name: Build Xiaomi Mix2s (Based AOSP A16) (test)

on:
  workflow_call:
  workflow_dispatch:

env:
  # 自定义内核编译时间变量 (支持标准日期格式)
  KBUILD_BUILD_TIMESTAMP: "2026-08-5 12:00:00"
  # 自定义编译者与主机名伪装 (可选)
  KBUILD_BUILD_USER: "builder"
  KBUILD_BUILD_HOST: "mi-server"

  DEVICE_NAME : "xiaomi_mix2s"
  DEVICE_CODENAME : "polaris"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/duckyduckG/android_kernel_xiaomi_sdm845_419.git"
  KERNEL_BRANCH : "lineage-23.2_xiaomi"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/sdm845-perf_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "resukisu" 

  SUSFS_ENABLE : true
  SUSFS_FIXED : true

  AK3_SOURCE : "https://github.com/JackA1ltman/OP8_AnyKernel3.git"
  AK3_BRANCH : "main"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "based_aosp_a16_4.19"

  PYTHON_VERSION: "3" 

  PACK_METHOD: "Anykernel3" 
  PACK_KMODULES: "false" 

  KERNELSU_METHOD: "shell" 

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" 
  PATCHES_BRANCH: "mi_kernel" 

  SUSFS_FOLDER_FIXED: "mix2s_aosp_a15_419" 
  SUSFS_PATCH_FIXED: "susfs_fixed" 

  REKERNEL_ENABLE: "false" 
  DROIDSPACES_ENABLE: "true" 
  NOMOUNT_ENABLE: "false" 

  HOOK_METHOD: "syscall" 

  KERNEL_PATCH: "false" 

  KPM_ENABLE: "false" 
  KPM_INLINE: "false" 
  KPM_KPATCH_NEXT: "false" 
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" 

  BASEBAND_GUARD_ENABLE: "false" 
  BASEBAND_GUARD_BOOT: "false" 

  GENERATE_DTB: "false" 
  GENERATE_CHIP: "qcom" 

  BUILD_DEBUGGER: "false" 
  SKIP_PATCH: "false" 

  BUILD_OTHER_CONFIG: "true" 
  MERGE_CONFIG_FILES: "vendor/xiaomi/sdm845-common.config,vendor/xiaomi/polaris.config"

  FREE_MORE_SPACE: "false" 

jobs:
  build-kernel:
    name: Xiaomi Mix2s (Based AOSP A16) (test)
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Checkout custom repository
        uses: actions/checkout@v4
        with:
          path: custom_repo

      - name: Checkout upstream repository
        uses: actions/checkout@v4
        with:
          repository: JackA1ltman/NonGKI_Kernel_Build_2nd
          ref: mainline
          path: upstream_repo

      - name: Sync upstream resources
        run: |
          cp -r upstream_repo/Patches ./
          cp -r upstream_repo/Bin ./
          chmod -R +x ./Bin/
      - name: Compilation environment preparation
        uses: ./upstream_repo/.github/workflows/build-env

      - name: Get neccssary tools
        uses: ./upstream_repo/.github/workflows/build-ready

      - name: Patch Kernel of SUSFS
        uses: ./upstream_repo/.github/workflows/patch-susfs

      - name: Patch for no-kprobe
        uses: ./upstream_repo/.github/workflows/patch-no-kprobe

      - name: Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          
          cp $GITHUB_WORKSPACE/custom_repo/Custom_Files/gpucc-sdm845.c drivers/clk/qcom/gpucc-sdm845.c
          cp $GITHUB_WORKSPACE/custom_repo/Custom_Files/sdm845-v2.dtsi arch/arm64/boot/dts/qcom/sdm845-v2.dtsi
          cp $GITHUB_WORKSPACE/custom_repo/Custom_Files/vdd-level-sdm845.h drivers/clk/qcom/vdd-level-sdm845.h
          cp $GITHUB_WORKSPACE/custom_repo/Custom_Files/devfreq.c drivers/devfreq/devfreq.c
          
          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_LTO_NONE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_SHADOW_CALL_STACK=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_RELR=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          
          echo "CONFIG_EROFS_FS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_EROFS_FS_ZIP=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_EROFS_FS_XATTR=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_EROFS_FS_POSIX_ACL=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_EROFS_FS_SECURITY=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          
          git config --global user.email "bot@github.actions"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Inject custom parameters to resolve dirty flag"
      - name: Patch Kernel of Re:Kernel
        uses: ./upstream_repo/.github/workflows/patch-rekernel

      - name: Patch Kernel of Droidspaces
        uses: ./upstream_repo/.github/workflows/patch-droidspaces

      - name: Patch Kernel of Baseband Guard
        uses: ./upstream_repo/.github/workflows/patch-baseband-guard

      - name: Build Process
        uses: ./upstream_repo/.github/workflows/build-process

      - name: Pack Process
        uses: ./upstream_repo/.github/workflows/pack-process

      - name: Upload Artifacts
        uses: ./upstream_repo/.github/workflows/upload-files
